description=OpenNLP POS-aware lemmatizer token filter for OpenSearch
version=${project.version}
name=opensearch-analysis-opennlp-lemmatizer
classname=io.github.radeno.lemmatizer.opensearch.OpenSearchOpenNlpPlugin
java.version=25
opensearch.version=${opensearch.version}
