description=OpenNLP POS-aware lemmatizer token filter for Elasticsearch
version=${project.version}
name=elasticsearch-analysis-opennlp-lemmatizer
classname=io.github.radeno.lemmatizer.elasticsearch.ElasticsearchOpenNlpPlugin
java.version=25
elasticsearch.version=${elasticsearch.version}
